### ISSUE TITLE
Blog Procédural

### ISSUE THREAD

**Issue by gurnavdeep** [NegreriePaul/GitHubInit#11]
Du fait du temps qu'il nous reste pour le projet et de notre planning chargé (école + entreprise) on va passer le blog en procédural pour avoir un gain de temps, tout en faisant du code propre.

**Comment by gurnavdeep** [comment]
Blog almost done. We have to do Comment section (insert, delete and update). And Unit testing also for now

**Comment by thomas-dudoux** [comment]
Blog isn't in MVC style so we can't test anything.
